x-common: &common
  restart: always
  env_file:
    - .env

x-common-volumes: &common-volumes
  volumes:
    - ./app:/app/app
    - ./call_llm:/app/call_llm
    - ./alembic:/app/alembic
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/app/.env
    - ./entrypoint.sh:/app/entrypoint.sh
    - ./data:/app/data

services:
  db:
    image: postgres:16
    <<: *common
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      PGTZ: Asia/Ho_Chi_Minh
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./mount-data/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5555:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 10

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    <<:
      - *common
      - *common-volumes
    command: [ "alembic", "upgrade", "head" ]
    restart: "no"
    depends_on: 
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    <<:
      - *common
      - *common-volumes
    ports:
      - 7777:7777
    command: [ "/app/entrypoint.sh" ]
    depends_on:
      db:
        condition: service_healthy
